# mPaaS Pods Begin
plugin "cocoapods-mPaaS"
source "https://code.aliyun.com/mpaas-public/podspecs.git"
#use_pod_for_mPaaS!
#mPaaS_baseline 'x.x.x'  # 请将 x.x.x 替换成真实基线版本
# mPaaS Pods End
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MPCdpDemo_pod' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MPCdpDemo_pod

  mPaaS_pod 'mPaaS_MobileFramework', '10.1.60'
  mPaaS_pod 'mPaaS_CDP', '10.1.60'
  mPaaS_pod 'mPaaS_CommonUI', '10.1.60'

end
